### ISSUE TITLE
after make on Linux Mint Cinnamon - always get these messages

### ISSUE THREAD

**Issue by MatrixMike** [paulscottrobson/neo6502-firmware#478]
Python 3.10.12
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 996, in version
    return distribution(distribution_name).version
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 969, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 548, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for gitpython
make: *** [Makefile:117: emulator-deps-nix] Error 1

**Comment by paulscottrobson** [comment]
gitpython is a requirement ; I think it is in python3-git or you can install it with PIP
